name: Discord Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord
        run: |
          COMMIT="${{ github.event.head_commit.message }}"
          REPO="${{ github.repository }}"

          if [ -z "$COMMIT" ]; then
            COMMIT="No commit message"
          fi

          curl -H "Content-Type: application/json" \
          -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -d "{\"content\":\"📦 Repo: $REPO\n📝 $COMMIT\"}"
